### ISSUE TITLE
mobile demo not working (scroll vertically)

### ISSUE THREAD

**Issue by criesner** [Stereobit/dragend#26]
The mobile demo is not working on my iphone5 or other emulator tools.
You can swipe left and right but can not scroll vertically. 

If you look at the demo on desktop it appears to work because you can scroll the page with the mousewheel however on touch devices you can not click drag the vertically.

Any fixes to this problem?
thanks,
-chris

**Comment by murito** [comment]
Hi i found a new problem in the solution of @netdust , when i click in any element, the dragend  function not work more.

regards!

**Comment by murito** [comment]
I know that this is closed but i dont know where write. I found that when you click any element, the function of dragend not work more, but if you add "this._afterScrollTransform.call();" on the onDragEnd, this works newly. Maybe you want add this trick to the plugin.

**Comment by ptisdel** [comment]
I solved this; in the _onMove function, right below "event = event.originalEvent || event;" simply add:

               var coords = getCoords(event),
                    x = this.startCoords.x - coords.x,
                    y = this.startCoords.y - coords.y;

                if (Math.abs(y) > Math.abs(x)) return;

**Comment by PowrSlave** [comment]
@ptisdel great job it seems to work so far!
